### ISSUE TITLE
stackSubgroupsWithInnerStack allocates space for items that are not displayed

### ISSUE THREAD

**Issue by knokit** [visjs/vis-timeline#115] opened 2019-09-30 12:31 UTC
`stackSubgroupsWithInnerStack` stacks all items within the subgroup, even the ones that are not displayed, which causes big gaps in the timeline (see animation below).

Shouldn't it stack only the items that are visible?

![stackSubgroupsWithInnerStack_issue](https://user-images.githubusercontent.com/3659829/65878158-b189c200-e38d-11e9-8d28-e947b68ff6a4.gif)

**Comment by mojoaxel** [comment] 2019-09-30 20:22
This behavior could also be reproduces using the [subgroups example](https://visjs.github.io/vis-timeline/examples/timeline/groups/subgroups.html).

**Comment by yotamberk** [comment] 2019-11-09 17:58
Since https://github.com/visjs/vis-timeline/pull/157 has been merged, It seems that this issue is not longer reproducible. Can you please confirm and close the issue if so?

**Comment by knokit** [comment] 2019-11-12 13:06
It seems to me that it didn't improve.. I still see it allocating space for items that are not visible.

It is still reproducible using the [subgroups example](https://visjs.github.io/vis-timeline/examples/timeline/groups/subgroups.html), with stacking enable.

**Comment by yotamberk** [comment] 2019-11-23 19:29
@knokit the timeline takes in consideration a margin back and forward from the time range visible in the timeline. I think the margin is about a third of the current time range for each side. Could that maybe be the reason you see the gap? Do you think this is not good behavior?

**Comment by knokit** [comment] 2019-11-25 15:45
@yotamberk, I think the gaps are a result of trying to stack all items (including non visible ones) inside the subgroups (see my PR).

Maybe, it would also be nice to be able to set that `interval` through the options.

**Comment by yotamberk** [comment] 2019-12-06 16:47
Fixed with  #211

**Closed by yotamberk** 2019-12-06 16:47 UTC
Labels: enhancement, waiting for re-check
