### ISSUE TITLE
Memory leak when using JSX in templates

### ISSUE THREAD

**Issue by Matthijs-Brouwer** [visjs/vis-timeline#1211] opened 2021-08-20 08:27 UTC
Hi,

I am using the vis-js timeline library and I would like to use JSX in the template option as shown in the [example](https://github.com/visjs/vis-timeline/blob/master/examples/timeline/other/usingReact16.html).
I use a combination of ReactDOM.createPortal and ReactDOM.render to create a template for all my items.

```js
const options = {
  template: (item, element) => {
    return ReactDOM.createPortal(
      ReactDOM.render(<Tag key={item.id}>item.id</Tag>, element),
      element
    );
  },
};

```

This seems to be causing a memory leak. Over time the number of `Detached HTMLDivElements` grows until I run out of memory.  
When I change the code to regular javascript the memory usage seems fine.

```js
const options = {
  template: (item, element) => {
    return "<div key={item.id}>item.id</div>";
  },
};
```

As I understand from [this](https://reactjs.org/docs/react-dom.html) page I should not be using the ReactDOM.CreatePortal in this case because the Timeline and the items in it are children of my own DOM node. But when I leave it out I get the same error as reported [here](https://github.com/almende/vis/issues/3592).
I am curious what causes this memory leak and how I could avoid it. Especially since the combination of ReactDOM.CreatePortal and ReactDOM.Render are used in the previously mentioned example.

**Comment by Fanna1119** [comment] 2021-11-30 19:36
Would it be possible that the cause is that you are not destroying the template when required?

**Comment by mojoaxel** [comment] 2023-09-02 20:43
This looks like a react issue to me.

**Comment by EvertTheman** [comment] 2023-09-04 06:39
This issue is from 2 years ago, I Think it should be fine to close it.

**Comment by Matthijs-Brouwer** [comment] 2023-09-04 06:41
This issue is from 2 years ago, I Think it should be fine to close it.

**Closed** 2023-10-04 09:13 UTC
Labels: question

**Comment by bh0mbalziyad** [comment] 2024-03-15 04:07
This issue is still present. I would expect this to work if you guys mention in your documentation that React templates are supported.
