### ISSUE TITLE
Remove Shapes4FREE icons

### ISSUE THREAD

**Issue by Thomaash** [visjs/vis-timeline#89] opened 2019-09-13 10:10 UTC
These icons are never used and atop of that their license doesn't allow redistribution. They should be removed from the codebase.

These icons are in `docs/img/external-link-icons`.

**Comment by mojoaxel** [comment] 2019-09-14 20:52
duplicate of https://github.com/visjs/vis-network/issues/116

**Closed** 2019-10-18 13:29 UTC
Labels: bug, good first issue, help wanted
