### ISSUE TITLE
Adding hidden dates to options causes horizontal scroll issues

### ISSUE THREAD

**Issue by data-handler** [visjs/vis-timeline#1282] opened 2021-11-07 22:41 UTC
* Which vis-component you are referring to: timeline
* Version: 7.5.0
* Browser / OS: Chrome / Mac OS Monterey
* Minimal code example: [jsbin](https://jsbin.com/badoralowa/edit?html,js,output)
* Description of issue:

When supplying hiddenDates array and setting horizontalScroll true, I am experiencing strange zooming when scrolling. i.e. horizontalScroll does not appear to be compatible with hiddenDates option.

**Comment by mojoaxel** [comment] 2023-09-02 21:08
closing as duplicate of #1243

**Closed by mojoaxel** 2023-09-02 21:08 UTC
Labels: bug, duplicate
