### ISSUE TITLE
Graph2D examples are broken

### ISSUE THREAD

**Issue by kreegahbundolo** [visjs/vis-timeline#783] opened 2020-11-11 10:09 UTC
A lot of the examples for Graph2D seems to be broken. Take a look at the web site, most examples are blank:

https://visjs.github.io/vis-timeline/examples/graph2d/

Can this be related to the issue with using DataSet for initialization / data loading?

**Comment by m-harnish** [comment] 2020-11-19 23:23
This seems to be a dup of https://github.com/visjs/vis-timeline/issues/652

**Comment by mojoaxel** [comment] 2021-03-17 10:59
closing as a duplicate of #652

**Closed by mojoaxel** 2021-03-17 10:59 UTC
Labels: bug, duplicate
