### ISSUE TITLE
Moment.js deprecation in favour of modern date handling library

### ISSUE THREAD

**Issue by michealroberts** [visjs/vis-timeline#1521] opened 2022-09-12 07:45 UTC
I'd like to propose that we deprecate the dependency to moment.js across all of the visas sub-projects, in favour of either:

- [day.js](https://day.js.org/en/)
- [date-fns](https://date-fns.org) 

I'd be firmly in favour of day.js as the preferred choice, and I am happy to make the necessary contributions, however complex or time consuming, to making this a reality.

I'm coming from purely an upstream usage, where we are looking to drop moment.js support across our technical stack.I believe others should start to follow suit.

The have a comprehensive guide as to why moment.js should be deprecated: https://momentjs.com/docs/ on their documentation website.

Let me know your thoughts, and preferences, with regards to the above.

Many thanks! 🙂

**Comment by Glandos** [comment] 2022-09-26 15:05
Duplicate of #672

**Comment by mojoaxel** [comment] 2023-09-02 20:20
closing as duplicate of #672

**Closed by mojoaxel** 2023-09-02 20:20 UTC
