### ISSUE TITLE
When groups more 400 amount, page loading is worst.

### ISSUE THREAD

**Issue by ko22009** [visjs/vis-timeline#210] opened 2019-11-25 15:18 UTC
Do you can realize by fastdom?
http://wilsonpage.github.io/fastdom/examples/animation.html

**Comment by ko22009** [comment] 2019-11-25 15:41
I noticed that if you create timeline with empty groups and items and after that add items to items and groups Dataset, after that bind to timeline. You HTML-DOM work normally.

**Comment by yotamberk** [comment] 2019-12-07 20:01
I don't understand what the issue is. Can you explain better what you expect?

**Comment by ko22009** [comment] 2019-12-08 11:14
Browser is freezing, if you add about 1000 amounts of items and groups. If you set group and items at the beginning and after that call add in group and item, you browser will be redrawing.

**Comment by yotamberk** [comment] 2019-12-14 21:07
I'm sorry but I still don;t understant the issue.
Please supply a jsbin to show what you mean.

**Comment by yotamberk** [comment] 2020-01-31 12:50
Closing until a jsbin for reproduction is supplied.

**Closed by yotamberk** 2020-01-31 12:50 UTC
Labels: bug, waiting for response
