### ISSUE TITLE
Error in Graph2.js in 06_interpolation.js sample

### ISSUE THREAD

**Issue by SteMMo33** [visjs/vis-timeline#46] opened 2019-08-11 14:04 UTC
Hi all,
I've just downloaded the last vis-timeline repo by git tool.
I'm taking a look to this sample and running on Firefox I see an error on the browser console:

TypeError: a.itemSet is undefined[Ulteriori informazioni] Graph2d.js:141:8

PS: I'm looking for a library to draw a chart that allows to drag every point of a chart; is there a sample that does it?

**Comment by mojoaxel** [comment] 2019-08-11 14:10
I can confirm this bug in [the 06_interpolation example](https://visjs.github.io/vis-timeline/examples/graph2d/06_interpolation.html):

```
Uncaught TypeError: Cannot set property 'initialDrawDone' of undefined
    at wt.<anonymous> (Graph2d.js:141)
    at wt.Ve.emit (index.js:134)
    at wt.Qe._redraw (Core.js:1062)
    at wt.<anonymous> (Core.js:139)
    at wt.Ve.emit (index.js:134)
    at _onResize (Core.js:1242)
```

**Comment by mojoaxel** [comment] 2019-08-11 14:18
> PS: I'm looking for a library to draw a chart that allows to drag every point of a chart; is there a sample that does it?

I don't think so. Maybe this helps: https://gist.github.com/niclasmattsson/7bceb05fba6c71c78d507adae3d29417

**Comment by mojoaxel** [comment] 2019-08-11 20:31
duplicate of #25

**Closed by mojoaxel** 2019-08-11 20:31 UTC
Labels: bug
