### ISSUE TITLE
Vertical scroll direction backwards (bugged) on Firefox

### ISSUE THREAD

**Issue by mmarko13** [visjs/vis-timeline#1163] opened 2021-07-13 19:04 UTC
Click&drag on the scrollbar in Firefox does not work properly (inverted).

When using the example from the official [site](https://visjs.github.io/vis-timeline/examples/timeline/groups/visibleGroups.html), it works properly on Chrome, while it works very strangely on Firefox (if you grab the scrollbar and drag it to scroll, it jumps back and forth between new position and the starting position).

This problem only exists if scrollbar is clicked and dragged, when scrolled with the mouse wheel, it works normally.

**Comment by melloware** [comment] 2021-08-05 11:36
Duplicate of this bug: https://github.com/visjs/vis-timeline/issues/135

**Comment by mojoaxel** [comment] 2023-09-02 21:06
closing as duplicate of #135

**Closed by mojoaxel** 2023-09-02 21:06 UTC
Labels: bug, duplicate
